import content from './data/content.json' with { type: 'json' };
import pressModel from './data/press-decision-model.json' with { type: 'json' };
import authoredDialogues from './data/case-dialogues.json' with { type: 'json' };
import runtimeDialogue from './data/runtime-dialogue.json' with { type: 'json' };

history.scrollRestoration='manual'; window.scrollTo(0,0);

const $ = (s) => document.querySelector(s);
const state = { scene: 'E02', caseId: 'C13', evidence: 0, dossierEvidence: 0, tags: {}, evidenceTags: [], marks: [], memos: [], documentsRead: [], relationships: {}, reputation: 0, invitation: false, encounters: [], rank: 10, access: ['intake'] };
const sceneData = Object.fromEntries(content.scenes.map(s => [s.id, s]));
const endings = Object.fromEntries(content.endings.map(e => [e.id, e]));
window.__chanceryContent = content;
const caseData = Object.fromEntries(pressModel.cases.map(c => [c.id, c]));
const dialogueData = Object.fromEntries(runtimeDialogue.cases.map(c => [c.id, c.lines]));

const sceneText = {
  E01: { date:'1836년 9–11월', collection:'Телескоп · Москва', title:'Первое<br/>философическое письмо', sub:'모스크바에서 발행된 글이 상트페테르부르크의 행정 파일이 되다', paperDate:'сентябрь 1836', slip:'№ 03', speaker:'모스크바 발행 기록', dialogue:'이 문서는 Петербург에서 인쇄된 것이 아니다. 그러나 Петербург의 서류철은 이 종이를 놓치지 않는다.', instruction:'발행지와 행정 처리지를 나누어 등록하십시오.', stamp:'모스크바 발행' },
  E02: { date:'1847년 1월 14일', collection:'Сѣверная пчела', title:'Насильный<br/>брак', sub:'사적인 이야기가 국가의 문제로 읽히는 순간', paperDate:'14 января 1847', slip:'№ 17', speaker:'니키텐코의 일기 여백', dialogue:'도시에서는 이미 이 혼인을 이야기하지만, 종이는 아직 집안일에 관한 글인 척합니다.', instruction:'표시된 문장을 읽고, 문서의 처리 방식을 정하십시오.', stamp:'검토 중' },
  E03: { date:'1847년', collection:'Современник · редакционная папка', title:'편집부<br/>교정 기록', sub:'문학적 거절 · 검열 위험 · 발행인과 편집자의 이견', paperDate:'1847', slip:'№ 28', speaker:'편집부 전달 메모', dialogue:'같은 글도 편집부에서는 문체의 문제이고, 관청에서는 위험의 문제가 된다.', instruction:'교정쇄의 문장과 편집자의 판단을 나누어 기록하십시오.', stamp:'교정쇄 대조' },
  E04: { date:'1847년 7월 5–8일', collection:'Канцелярская копия', title:'Приказъ<br/>5 июля', sub:'Шевченко · Кулиш · Костомаров', paperDate:'5–8 июля 1847', slip:'№ 42', speaker:'관청 서기관', dialogue:'의견을 적지 마십시오. 명령서가 우리 손을 거쳐 갔다는 사실을 적으십시오.', instruction:'명령의 처리와 전달 방식을 기록하십시오.', stamp:'7월 8일' },
  E05: { date:'1847년', collection:'Письмо / редакционная папка', title:'공개 지면과<br/>사적 편지', sub:'벨린스키 ↔ 고골 · 문서와 전달의 흔적', paperDate:'1847', slip:'№ 57', speaker:'편지 봉투의 흔적', dialogue:'지면에서의 비평과 봉투 안의 말은 같은 손으로도 다른 위험을 가진다.', instruction:'편지·책·전달 흔적을 따라 두 사람의 관계를 읽으십시오.', stamp:'간접 연결' },
  E06: { date:'1848년 2–4월', collection:'Комитет 2 апреля · 비밀 검토', title:'인쇄된 뒤에도<br/>끝나지 않는 검열', sub:'유럽 혁명 소식과 비밀 검토의 확대', paperDate:'2 апреля 1848', slip:'№ 74', speaker:'비밀 검토 지시서', dialogue:'인쇄 전의 문장만이 문제가 아니다. 이미 읽힌 종이도 다시 관청으로 돌아온다.', instruction:'사후 검토와 감시가 무엇을 바꾸는지 메모하십시오.', stamp:'비밀 검토' },
  E07: { date:'1849년', collection:'Дѣло о тайномъ обществѣ', title:'Досье<br/>Петрашевскаго', sub:'посѣщеніе · владѣніе · переписка · чтеніе', paperDate:'1849', slip:'№ 91', speaker:'수사 기록 메모', dialogue:'방문, 소지, 소리 내어 읽기. 이 기록에서는 서로 다른 행동의 경계가 위험할 만큼 좁아집니다.', instruction:'파일에 남길 행동을 표시하십시오.', stamp:'증거' }
};
const documentText = { E01:['Телескоп. Журнал современного просвещения. № 15, Москва, 1836.','<mark data-source="SRC-E01-TELESKOP">Первое философическое письмо</mark> — публикация, не петербургская улика 현장.','기록은 발행지와 행정 처리지를 분리해 보존한다.'], E02:['Есть союзы, заключённые не сердцем, а печатью. В них каждый день кажется мирным, пока сосед не прочтёт договор вслух.','Редактор оставляет слова на месте; читатель знает, куда они смотрят. <mark data-source="SRC-E02-PCH">Отметьте место, где частное перестаёт быть частным.</mark>','Въ типографской комнате пахнетъ свинцомъ, мокрой шерстью и ожиданиемъ.'], E03:['교정쇄: Современник 1847. 편집부의 문장과 검열상 위험을 같은 칸에 넣지 않는다.','<mark data-source="SRC-SOV-1847">편집자의 거절</mark>과 관청의 우려는 서로 다른 기록으로 남는다.','먼저 처리할 원고에는 날짜와 전달자를 함께 적는다.'], E04:['Копия приказа: сочинения, изображения и имя автора подлежат особому наблюдению. Бумага движется быстрее, чем разъяснение.','Петербургский комитет получил сообщение 8 июля. <mark data-source="SRC-SHEV-ORD">Объявления запрещены до дальнейшего распоряжения.</mark>','На полях остаётся только дата, подпись и след прошедшей руки.'], E05:['편지 봉투, 책의 여백, 지인의 전달 메모. 직접 대면은 주장하지 않는다.','<mark data-source="SRC-SOV-1847">Белинский의 공개 비평</mark>과 Gogol에게 간 사적 문서를 나란히 읽는다.','관계는 얼굴이 아니라 종이의 이동으로 드러난다.'], E06:['Комитет 2 апреля. 유럽의 혁명 소식 뒤, 이미 인쇄된 종이도 다시 검토 대상이 된다.','<mark data-source="SRC-COM-1848">비밀 검토 지시</mark>는 검열 자체를 바라보는 시선까지 문서화한다.','이 파일에는 사후 처리 일자와 보고 계통을 남긴다.'], E07:['Входил ли он? Держал ли лист? Переписывал ли строку? Следствие собирает действия, не намерения.','<mark data-source="SRC-PET-1849">Посещение · владение · переписка · чтение вслух</mark> — четыре разных веса в одном деле.','Фамилии настоящих людей остаются в архиве; ваш след здесь — реконструкция.'] };
const drawerText = { E01:['SRC-E01-TELESKOP','Телескоп №15 · Москва · 1836년 9월','모스크바에서 발행된 차다예프의 첫 철학적 서한입니다.','https://feb-web.ru/feb/kle/kle-abc/ke7/ke7-4531.htm?cmd=p&istext=1','SRC-E01-TELESKOP','차다예프 첫 철학적 서한','발행지와 행정 처리지가 갈라지는 기록입니다.','https://feb-web.ru/feb/kle/kle-abc/ke7/ke7-4531.htm?cmd=p&istext=1'], E02:['SRC-E02-PCH','НЭБ / Северная пчела · 1847년 1월 14일','11호 「Насильный брак」의 표제와 관련 기록입니다.','https://rusneb.ru/','SRC-NIK-1847','А. В. 니키텐코 일기 · 1847년 1월 18일','상트페테르부르크의 소문과 공식 반응을 보여주는 일기 자료입니다.','https://runivers.ru/'], E03:['SRC-SOV-1847','Современник · 1847년 호 자료','실제 호수와 편집 자료를 바탕으로 문학적 판단과 검열 위험을 나눕니다.','https://rusneb.ru/','SRC-SOV-1847','편집부 기록','편집실에서 오간 판단의 흔적입니다.','https://rusneb.ru/'], E04:['SRC-SHEV-ORD','RGIA 자료철 · 1847년 7월 5일','5일 명령과 8일 광고 금지 통지가 담긴 행정 기록입니다.','https://fgurgia.ru/','SRC-SHEV-ORD','같은 자료철 · 행정 기록','명령이 전달된 순서와 날짜를 확인합니다.','https://fgurgia.ru/'], E05:['SRC-SOV-1847','Современник / 편지 자료 · 1847','공개 비평과 사적 편지가 오간 경로를 보여주는 자료입니다.','https://rusneb.ru/','SRC-SOV-1847','간접 연결 기록','편지·책·전달 흔적을 따라 관계를 읽습니다.','https://rusneb.ru/'], E06:['SRC-COM-1848','4월 위원회 · 1848년 4월 2일','유럽 혁명 뒤 비밀 검토가 확대된 행정 자료입니다.','https://runivers.ru/','SRC-COM-1848','비밀 검토 자료','인쇄 뒤에도 이어진 검토 절차를 확인합니다.','https://runivers.ru/'], E07:['SRC-PET-1849','제국 수사 기록철 · 1849년','방문·소지·필사·낭독을 구분해 적은 수사 기록철입니다.','https://runivers.ru/','SRC-PET-1849','같은 자료철 · 수사 기록','행동의 차이가 수사 기록에서 어떻게 무게를 얻는지 보여줍니다.','https://runivers.ru/'] };
function renderScene(id) { const t=sceneText[id]; state.scene=id; document.querySelectorAll('.ledger-line').forEach(x=>x.classList.toggle('active',x.dataset.scene===id)); $('#dateLabel').textContent=t.date; $('#paperCollection').textContent=t.collection; $('#paperTitle').innerHTML=t.title; $('#paperSub').textContent=t.sub; $('#paperDate').textContent=t.paperDate; $('#slipNo').textContent=t.slip; $('#speaker').textContent=t.speaker; $('#dialogue').textContent=t.dialogue; $('#instruction').textContent=t.instruction; $('#paperStamp').textContent=t.stamp; $('#paper').querySelector('.paper-footer span:first-child').textContent=`자료철 · ${id}`; $('#paperColumns').innerHTML=documentText[id].map(x=>`<p>${x}</p>`).join(''); $('#drawerKicker').textContent=`자료 서랍 / ${id}`; const d=drawerText[id]; ['sourceIdA','sourceMetaA','sourceContextA','sourceLinkA','sourceIdB','sourceMetaB','sourceContextB','sourceLinkB'].forEach((key,i)=>{const el=$(`#${key}`); if(i===3||i===7) el.href=d[i]; else el.textContent=d[i];}); const ref={E01:['https://upload.wikimedia.org/wikipedia/commons/c/ca/Anichkov-1830.jpg','Wikimedia Commons · Anichkov panorama · 공개 참고 이미지'],E02:['',''],E03:['',''],E04:['',''],E05:['',''],E06:['',''],E07:['','']}[id]; $('#referenceImage').hidden=!ref[0]; if(ref[0]){ $('#referenceImage').src=ref[0]; $('#referenceCaption').textContent=ref[1]; } else $('#referenceCaption').textContent='이 장면은 문서와 기록을 중심으로 읽습니다.'; $('#responseArea').hidden=false; $('#choiceArea').hidden=true; $('#reply').value=''; $('#reply').placeholder=id==='E07'?'파일에 남길 행동을 쓰십시오…':'문서철에 남길 한 문장을 쓰십시오…'; }
function updateRouteState(){ const person=state.relationships.editor>0?'편집부와 접촉':'관청 내부 전달'; const invite=state.invitation?'편집실 초대 기록 있음':'사적 모임 초대 없음'; const access=state.rank<10?'교정쇄·상관 보고 접근':'접수·등록 접근'; $('#routeState').innerHTML=`<b>현재 경로</b><span>${person} · 평판 ${state.reputation>=1?'우호적':'유보적'} · ${invite}<br/>관등 ${state.rank}등관급 · ${access}</span>`; }
function maybePromote(){ if(state.rank===10&&state.evidence>=3&&state.reputation>=2){state.rank=9; state.access.push('proof-review','supervisor-report'); if(!state.memos.some(m=>m.scene==='PROMOTION')) state.memos.push({scene:'PROMOTION',text:'관등 기록: 교정쇄 대조와 상관 보고 접근이 열렸다.',date:'1847'}); } updateRouteState(); }
function applyRouteEffects(hits){ if(hits.includes('press_freedom')){ state.relationships.editor=(state.relationships.editor||0)+1; state.invitation=true; state.reputation++; if(!state.encounters.includes('editorial-room'))state.encounters.push('editorial-room'); } if(hits.includes('legalism')){ state.relationships.committee=(state.relationships.committee||0)+1; state.reputation++; if(!state.encounters.includes('committee-desk'))state.encounters.push('committee-desk'); } if(hits.includes('risk_tolerance'))state.reputation--; maybePromote(); }
function addTag(tag) { state.tags[tag]=(state.tags[tag]||0)+1; state.evidence++; if(state.scene==='E07'&&['attendance','copying','correspondence'].includes(tag)) state.dossierEvidence++; state.evidenceTags.push(tag); $('#evidenceCount').textContent=state.evidence; const list=$('#markList'); if(list.querySelector('.empty-mark')) list.innerHTML=''; const el=document.createElement('div'); el.className='mark'; el.innerHTML=`<em>${tag.replaceAll('_',' ')}</em>대장에 표시를 보관했습니다`; list.append(el); updateRouteState(); }
function classify(text) { const t=text.toLowerCase(); const hits=[]; const rules=[['press_freedom',['свобод','прав','голос','печать','открыт','자유','비판','freedom']],['legalism',['закон','поряд','приказ','правил','запиш','법','명령','기록','law']],['westernism',['европ','запад','границ','유럽','국경','border']],['european_outlook',['유럽','유학','외국','europe','европ']],['slavophile_affinity',['народ','слав','общин','русск','전통','공동체']],['tradition_affinity',['전통','관습','정교','러시아성','традиц']],['state_loyalty',['국가','충성','관청','제국','государ','служб']],['social_reform',['народ','бедн','справедлив','개혁','농민','노예','reform']],['orthodoxy_attitude',['교회','신앙','정교회','православ']],['radicalism',['급진','혁명','봉기','радик','революц']],['risk_tolerance',['риск','тайн','скрыт','опас','위험','risk']]]; for(const [tag,words] of rules) if(words.some(w=>t.includes(w))) hits.push(tag); if(state.scene==='E07'){if(t.includes('참석')||t.includes('attendance'))hits.push('attendance');if(t.includes('복사')||t.includes('copy'))hits.push('copying');if(t.includes('서신')||t.includes('편지')||t.includes('correspondence'))hits.push('correspondence');} return hits.length?hits:['legalism']; }
function submit() { const value=$('#reply').value.trim(); if(!value) { $('#reply').focus(); return; } state.memos.push({scene:state.scene,text:value,date:sceneText[state.scene]?.date||caseData[state.caseId]?.year}); if(!state.documentsRead.includes(state.scene)) state.documentsRead.push(state.scene); const hits=classify(value); hits.forEach(addTag); applyRouteEffects(hits); $('#responseArea').hidden=true; const choices=$('#choiceArea'); choices.hidden=false; choices.innerHTML=''; const routeLabels={legalism:'법과 규정',press_freedom:'비판과 출판',westernism:'유럽 지향',slavophile_affinity:'러시아 전통',state_loyalty:'국가 충성',social_reform:'사회 개혁',risk_tolerance:'위험 감수'}; const options=state.scene==='CASE'?caseData[state.caseId].choiceRoutes.map(route=>[route,`처리 원칙: ${routeLabels[route]||route}를 기록한다.`]):state.scene==='E07'?[['attendance','기록: 참석은 방의 증거로 남긴다.'],['copying','기록: 필요한 말만 옮겨 적는다.'],['correspondence','기록: 편지는 모임과 같지 않다.']]:[['legalism','문서의 언어를 그대로 등록한다.'],['press_freedom','주의 깊은 독자가 비유를 읽게 둔다.'],['risk_tolerance','위험을 표시하고 문서를 통과시킨다.']]; options.forEach(([tag,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{addTag(tag); advance();};choices.append(b);}); }
function advance(){ const next={E01:'E02',E02:(state.tags.press_freedom||0)>0?'E03':'E04',E03:state.invitation?'E05':'E04',E04:'E05',E05:'E06',E06:'E07'}; if(next[state.scene]) renderScene(next[state.scene]); else showEnding(); }
function showEnding(){ let id='UVAROV'; if(state.dossierEvidence>=3) id='DOSTOEVSKY_PETRASHEVSKY'; else if((state.tags.press_freedom||0)>=2&&(state.tags.westernism||0)>=1) id='HERZEN'; else if((state.tags.press_freedom||0)>=2&&(state.tags.legalism||0)>=1) id='BELINSKY'; else if((state.tags.slavophile_affinity||0)>=2) id='KHOMYAKOV'; const e=endings[id]; const epilogue=`${e.epilogue||e.reconstructed}${content.epilogueAddenda?.[id]||''}`; $('#endingTitle').textContent=e.title; $('#endingDocumented').innerHTML=`<b>기록</b><br>${e.documented}`; $('#endingReconstructed').innerHTML=`<b>당신의 경로</b><br>${epilogue}<br><br><b>내가 남긴 메모</b><br>${state.memos.map(m=>`「${m.text}」`).join('<br>')||'없음'}`; $('#endingOverlay').hidden=false; }
function drawer(open){ $('#sourceDrawer').classList.toggle('open',open); $('#sourceDrawer').setAttribute('aria-hidden',String(!open)); $('#drawerBackdrop').hidden=!open; }
$('#evidenceBtn').onclick=()=>{const on=document.body.classList.toggle('evidence-mode'); $('#evidenceBtn').setAttribute('aria-pressed',String(on));}; window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h'&&!e.metaKey&&!e.ctrlKey) $('#evidenceBtn').click(); if(e.key==='Escape') drawer(false);}); $('#sourceBtn').onclick=()=>drawer(true); $('#closeDrawer').onclick=()=>drawer(false); $('#drawerBackdrop').onclick=()=>drawer(false); $('#translationBtn').onclick=()=>{const on=$('#paperTranslation').hidden; $('#paperTranslation').hidden=!on; $('#translationBtn').textContent=on?'번역 닫기':'한국어 번역 보기';}; $('#submitReply').onclick=submit; document.querySelectorAll('.ledger-line,[data-scene]').forEach(el=>el.onclick=()=>renderScene(el.dataset.scene)); $('#walkBtn').onclick=()=>{$('#walkOverlay').hidden=false; window.dispatchEvent(new Event('walk-open'));}; $('#finishWalk').onclick=()=>{$('#walkOverlay').hidden=true; renderScene(state.scene==='E02'?'E04':'E07');}; $('#saveBtn').onclick=()=>{localStorage.setItem('chancery-save',JSON.stringify(state)); $('#saveBtn').textContent='저장됨';}; $('#loadBtn').onclick=()=>{const saved=localStorage.getItem('chancery-save'); if(!saved)return; Object.assign(state,JSON.parse(saved)); $('#evidenceCount').textContent=state.evidence; updateRouteState(); renderScene(state.scene); $('#loadBtn').textContent='불러옴';}; $('#restart').onclick=()=>{state.evidence=0;state.dossierEvidence=0;state.tags={};state.evidenceTags=[];state.marks=[];state.memos=[];state.documentsRead=[];state.relationships={};state.reputation=0;state.invitation=false;state.encounters=[];state.rank=10;state.access=['intake'];$('#evidenceCount').textContent='0';$('#endingOverlay').hidden=true;updateRouteState();renderScene('E02');};
documentText.E01[1]='<mark data-source="SRC-E01-TELESKOP">Первое философическое письмо</mark> — 모스크바에서 발행된 글의 행정 기록입니다.';
documentText.E07[2]='파일에는 확인된 행동과 날짜를 남깁니다.';
const sceneTranslations={E01:'1836년 모스크바에서 발행된 「철학적 서한」입니다. 상트페테르부르크에서 인쇄된 문서가 아니라, 행정기관이 주목한 발행물로 등록합니다.',E02:'마음이 아니라 인장으로 맺어진 결합이 있습니다. 겉으로는 사적인 혼인 이야기지만, 이 문서는 독자가 그 너머의 국가와 관계를 읽도록 만듭니다.',E03:'편집자는 문장을 다듬고, 관청은 그 문장이 불러올 위험을 따집니다. 두 판단을 한 기록으로 섞지 않습니다.',E04:'명령의 사본에는 글과 그림, 작성자의 이름을 특별히 살피라는 지시가 적혀 있습니다. 종이는 해명보다 빠르게 이동합니다.',E05:'공개 비평과 사적인 편지는 같은 시대의 기록이지만 역할이 다릅니다. 사람 사이의 연결은 얼굴보다 종이의 이동으로 확인합니다.',E06:'유럽의 혁명 소식 뒤에는 이미 인쇄된 종이도 다시 검토 대상이 됩니다. 사후 검토의 날짜와 보고 계통을 남깁니다.',E07:'수사 기록은 의도가 아니라 행동을 구분합니다. 방문했는지, 문서를 가졌는지, 베껴 썼는지, 소리 내어 읽었는지를 따로 적습니다.'};
const baseSceneRender=renderScene;
renderScene=(id)=>{baseSceneRender(id);const translation=$('#paperTranslation p');if(translation)translation.textContent=sceneTranslations[id]||'현재 문서에 연결된 한국어 번역이 없습니다.';const task=$('#currentTask span');if(task)task.textContent=state.documentsRead.includes(id)?'표시한 문장을 검토한 뒤, 문서를 상신하거나 보류하십시오.':'한국어 번역을 확인한 뒤, 검토할 문장을 표시하십시오.';};
renderScene('E02');
function renderCase(caseId) { const c=caseData[caseId]; if(!c)return; state.caseId=caseId; state.scene='CASE'; $('#dateLabel').textContent=`${c.year}년 · 사건 ${c.id}`; $('#paperCollection').textContent='사건 등록철 · 러시아 제국'; $('#paperTitle').textContent=c.title; $('#paperSub').textContent='도착한 문서와 검토자의 판단을 차례로 대조합니다.'; $('#paperDate').textContent=c.year; $('#slipNo').textContent=c.casePackId; $('#speaker').textContent='전달 메모'; $('#dialogue').textContent=c.dialogueHook; $('#instruction').textContent=c.lead; $('#paperStamp').textContent='접수'; $('#paper').querySelector('.paper-footer span:first-child').textContent=`사건철 · ${c.id}`; $('#paperColumns').innerHTML=[...c.incoming,...c.review].map((x,i)=>`<p>${i<4?`<b>${i+1}. 도착 문서</b> `:'<b>검토</b> '}${x}</p>`).join('')+`<p class="faded-line"><b>상신</b> ${c.escalation}</p><p class="faded-line"><b>개인 메모</b> ${c.privateResponse}</p>`; $('#drawerKicker').textContent=`자료 서랍 / ${c.id}`; $('#sourceIdA').textContent=c.casePackId; $('#sourceMetaA').textContent=`${c.year} · ${c.title}`; $('#sourceContextA').textContent=`${c.incoming.length}건의 접수 문서와 ${c.review.length}건의 검토 항목이 연결된 사건 묶음입니다.`; $('#sourceLinkA').href='https://commons.wikimedia.org/'; $('#sourceIdB').textContent='CASE-DIALOGUE'; $('#sourceMetaB').textContent='대화 훅 · '+c.id; $('#sourceContextB').textContent=c.dialogueHook; $('#sourceLinkB').href='https://ru.wikisource.org/'; $('#referenceImage').hidden=true; $('#referenceCaption').textContent='이 사건의 문서 목록과 검토 항목을 자료 서랍에 정리했습니다.'; $('#responseArea').hidden=false; $('#choiceArea').hidden=true; $('#reply').value=''; $('#reply').placeholder='이 사건의 처리 원칙을 한 문장으로 쓰십시오…'; document.querySelectorAll('.ledger-line').forEach(x=>x.classList.remove('active')); $('#caseSelector').value=caseId; }
const caseSelector=document.querySelector('#caseSelector'); if(caseSelector){caseSelector.innerHTML=pressModel.cases.map(c=>`<option value="${c.id}">${c.id} · ${c.year} · ${c.title}</option>`).join(''); caseSelector.value=state.caseId; caseSelector.addEventListener('change',(event)=>renderCase(event.target.value));}
window.addEventListener('desk-prop', (event) => {
  const { id, label, action } = event.detail;
  const route = $('#routeState');
  if (route) route.innerHTML = `<b>${label}</b><span>${action}</span>`;
  const sourceMap={ledger:['대장 · 등록 번호와 전달 흔적','접수 번호와 상급자 전달 경로를 대조하는 책상 기록입니다.'],periodical:['정기간행물 · 해당 호','발행 호수와 문장 위치를 확인하는 원자료 묶음입니다.'],proof:['교정쇄 · 삭제와 첨가','편집자의 손과 검토 흔적을 읽는 문서입니다.'],envelope:['봉투 · 전달 경로','봉인과 수신 흔적을 확인하는 물질 자료입니다.'],folder:['공식 자료철 · 상신 문서','관청 안에서 문서가 이동한 순서를 정리합니다.'],drawer:['서랍 · 보관 기록','개인 메모와 도장을 꺼내 확인합니다.'],inkwell:['잉크병 · 필기 도구','서기관의 현장 기록에 사용한 문구류입니다.']};
  if(id&&sourceMap[id]){const [meta,context]=sourceMap[id]; $('#sourceIdA').textContent=`DESK-${id.toUpperCase()}`; $('#sourceMetaA').textContent=meta; $('#sourceContextA').textContent=context; $('#sourceLinkA').href='https://commons.wikimedia.org/'; $('#drawerKicker').textContent='자료 서랍 / 책상 소품'; drawer(true);}
});
const sourceReading={scene:'E02',sourceId:'SRC-E02-PCH',scanUrl:'',scanCaption:'НЭБ катал로그에서 호수와 서지 정보를 확인합니다.',transcription:'Отметьте место, где частное перестаёт быть частным.',translation:'사적인 이야기가 공적 기록으로 넘어가는 지점을 표시합니다.'};
function setSourceReading(packet){Object.assign(sourceReading,packet);$('#sourceScanImage').hidden=!sourceReading.scanUrl;if(sourceReading.scanUrl){$('#sourceScanImage').src=sourceReading.scanUrl;}$('#sourceScanCaption').textContent=sourceReading.scanCaption||'연결된 원문 자료';$('#sourceTranscription').textContent=sourceReading.transcription||'전사문을 확인할 수 있는 자료입니다.';$('#sourceTranslation').textContent=sourceReading.translation||'이 문장이 사건에서 어떤 역할을 하는지 기록합니다.';showSourceTab('scan');}
function showSourceTab(tab){const scan=tab==='scan',trans=tab==='transcription';$('#sourceScanImage').hidden=!scan||!sourceReading.scanUrl;$('#sourceScanCaption').hidden=!scan;$('#sourceTranscription').hidden=!trans;$('#sourceTranslation').hidden=scan||trans;document.querySelectorAll('.source-reading-tabs button').forEach(b=>b.classList.remove('active'));$(`#${scan?'scanTab':trans?'transcriptionTab':'translationTab'}`).classList.add('active');}
setSourceReading({scene:'E02',sourceId:'SRC-E02-PCH',scanUrl:'',scanCaption:'НЭБ катал로그에서 《Северная пчела》 1847년 1월 14일 호를 확인합니다.',transcription:'Редактор оставляет слова на месте; читатель знает, куда они смотрят.',translation:'편집자는 문장을 그대로 두지만, 독자는 그 문장이 향하는 곳을 알아봅니다.'});
$('#scanTab').onclick=()=>showSourceTab('scan');$('#transcriptionTab').onclick=()=>showSourceTab('transcription');$('#translationTab').onclick=()=>showSourceTab('translation');
$('#underlineAction').onclick=()=>{addTag('문장_표시');$('#paperStamp').textContent='표시됨';};$('#marginAction').onclick=()=>{state.memos.push({scene:state.scene,text:'자료 서랍에서 문장과 맥락을 함께 확인함',date:sceneText[state.scene]?.date||'사건 기록'});updateRouteState();};$('#stampAction').onclick=()=>{addTag('자료철_편입');$('#paperStamp').textContent='자료철 편입';};
const originalRenderScene=renderScene; renderScene=(id)=>{originalRenderScene(id);const text=documentText[id]||[];setSourceReading({scene:id,sourceId:drawerText[id]?.[0]||'CASE-SOURCE',scanUrl:id==='E01'?'https://upload.wikimedia.org/wikipedia/commons/c/ca/Anichkov-1830.jpg':'',scanCaption:id==='E01'?'공개 참고 이미지 · 상트페테르부르크 파노라마':'원문 자료는 자료기관 링크에서 확인합니다.',transcription:text.find(x=>!x.includes('<mark'))||'연결된 원문 발췌',translation:'이 문장이 문서 처리에서 어떤 역할을 하는지 살펴봅니다.'});};
document.querySelector('#caseSelector')?.addEventListener('change',(event)=>{const c=caseData[event.target.value];setSourceReading({scene:event.target.value,sourceId:c.casePackId,scanUrl:'',scanCaption:`${c.year}년 사건철의 연결 자료입니다. 원문 링크와 서지 정보를 확인하십시오.`,transcription:c.incoming[0]+'\n'+c.review[0],translation:c.lead});});
const originalRenderCase=renderCase; renderCase=(id)=>{const index=pressModel.cases.findIndex(c=>c.id===id);state.caseRunIndex=index<0?0:index;originalRenderCase(id);const c=caseData[id];setSourceReading({scene:id,sourceId:c.casePackId,scanUrl:'',scanCaption:`${c.year}년 사건철 · ${c.title}`,transcription:c.incoming.join('\n'),translation:c.lead});};
const originalAdvance=advance; advance=()=>{if(state.scene==='CASE'){if(!state.caseTurnPending){state.caseTurnPending=true;const c=caseData[state.caseId];$('#dialogue').textContent=`${c.dialogueHook} ${c.escalation}.`;$('#instruction').textContent='첫 판단 뒤, 문서가 실제로 움직이는 방식을 정하십시오.';const choices=$('#choiceArea');choices.innerHTML='';[['physical-forward','문서를 상급자 서류철에 넣는다.'],['physical-hold','봉투를 접어 개인 메모와 함께 보관한다.']].forEach(([tag,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{addTag(tag);state.turnPending=false;advance();};choices.append(b);});return;}const nextIndex=(state.caseRunIndex??0)+1;state.turnPending=false;if(nextIndex<10){state.caseRunIndex=nextIndex;renderCase(pressModel.cases[nextIndex].id);}else{renderScene('E07');}return;}originalAdvance();};
window.addEventListener('desk-prop',(event)=>{const id=event.detail.id;if(!id)return;const packet={ledger:['DESK-LEDGER','대장 기록','접수 번호·전달 순서를 대조하는 기록입니다.'],periodical:['DESK-PERIODICAL','잡지 지면','해당 호의 지면과 발행 정보를 확인합니다.'],proof:['DESK-PROOF','교정쇄','삭제 표시와 편집자의 손을 함께 읽습니다.'],envelope:['DESK-ENVELOPE','봉투와 전달 흔적','봉인과 수신 흔적을 기록합니다.']}[id];if(packet)setSourceReading({sourceId:packet[0],scanUrl:'',scanCaption:packet[1],transcription:packet[2],translation:'이 소품에서 확인한 기록을 현재 사건의 처리 근거로 남깁니다.'});});
$('#loadBtn').onclick=()=>{const saved=localStorage.getItem('chancery-save');if(!saved)return;Object.assign(state,JSON.parse(saved));$('#evidenceCount').textContent=state.evidence;updateRouteState();if(state.scene==='CASE')renderCase(state.caseId||'C01');else renderScene(state.scene);$('#loadBtn').textContent='불러옴';};
const caseRenderWithDialogue=renderCase; renderCase=(id)=>{caseRenderWithDialogue(id);const lines=dialogueData[id]||[];if(lines[0]){$('#speaker').textContent=lines[0].speaker;$('#dialogue').textContent=lines[0].text;}state.dialogueIndex=0;state.caseTurnPending=false;};
const advanceBeforeDialogue=advance; advance=()=>{if(state.scene==='CASE'){const lines=dialogueData[state.caseId]||[];if(!state.caseTurnPending){state.caseTurnPending=true;state.dialogueIndex=1;const line=lines[1]||lines[0];$('#speaker').textContent=line?.speaker||'전달 메모';$('#dialogue').textContent=line?.text||caseData[state.caseId].escalation;$('#instruction').textContent='첫 판단 뒤, 문서가 실제로 움직이는 방식을 정하십시오.';const choices=$('#choiceArea');choices.innerHTML='';[['physical-forward','문서를 상급자 서류철에 넣는다.'],['physical-hold','봉투를 접어 개인 메모와 함께 보관한다.']].forEach(([tag,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{addTag(tag);state.caseTurnPending=false;advance();};choices.append(b);});return;}const actionLine=lines[4]||lines[2];if(actionLine){$('#speaker').textContent=actionLine.speaker;$('#dialogue').textContent=actionLine.text;}state.caseTurnPending=false;advanceBeforeDialogue();return;}advanceBeforeDialogue();};
const dialogueRender=renderCase; renderCase=(id)=>{dialogueRender(id);state.dialoguePhase=0;};
const routeAdvance=advanceBeforeDialogue; advance=()=>{if(state.scene==='CASE'){const lines=dialogueData[state.caseId]||[];if(state.dialoguePhase===0){state.dialoguePhase=1;const line=lines[1]||lines[0];$('#speaker').textContent=line?.speaker||'전달 메모';$('#dialogue').textContent=line?.text||caseData[state.caseId].escalation;$('#instruction').textContent='첫 판단 뒤, 문서가 실제로 움직이는 방식을 정하십시오.';const choices=$('#choiceArea');choices.innerHTML='';[['physical-forward','문서를 상급자 서류철에 넣는다.'],['physical-hold','봉투를 접어 개인 메모와 함께 보관한다.']].forEach(([tag,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{addTag(tag);state.dialoguePhase=2;advance();};choices.append(b);});return;}const actionLine=lines[4]||lines[2];if(actionLine){$('#speaker').textContent=actionLine.speaker;$('#dialogue').textContent=actionLine.text;}state.dialoguePhase=0;const nextIndex=(state.caseRunIndex??0)+1;if(nextIndex<10){state.caseRunIndex=nextIndex;renderCase(pressModel.cases[nextIndex].id);}else renderScene('E07');return;}routeAdvance();};
const previousDialogueAdvance=advance; advance=()=>{if(state.scene!=='CASE'){previousDialogueAdvance();return;}const lines=dialogueData[state.caseId]||[];const show=(index,instruction,options)=>{state.dialoguePhase=index;const line=lines[index]||lines[lines.length-1];$('#speaker').textContent=line?.speaker||'전달 메모';$('#dialogue').textContent=line?.text||'';$('#instruction').textContent=instruction;const choices=$('#choiceArea');choices.innerHTML='';options.forEach(([tag,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{addTag(tag);advance();};choices.append(b);});};if(state.dialoguePhase===0){show(1,'첫 판단 뒤, 문서가 실제로 움직이는 방식을 정하십시오.',[['physical-forward','문서를 상급자 서류철에 넣는다.'],['physical-hold','봉투를 접어 개인 메모와 함께 보관한다.']]);return;}if(state.dialoguePhase===1){show(2,'상대가 남긴 두 번째 흔적을 어떻게 처리할지 고르십시오.',[['preserve-context','원문과 함께 맥락을 보존한다.'],['separate-context','추론 메모를 별도 종이에 옮긴다.']]);return;}if(state.dialoguePhase===2){show(3,'마지막으로 전달할 말과 파일의 경계를 정하십시오.',[['send-superior','상급자에게 근거와 함께 상신한다.'],['return-editor','편집부에 수정 의견을 돌려보낸다.']]);return;}const actionLine=lines[4]||lines[3];if(actionLine){$('#speaker').textContent=actionLine.speaker;$('#dialogue').textContent=actionLine.text;}state.dialoguePhase=0;const nextIndex=(state.caseRunIndex??0)+1;if(nextIndex<10){state.caseRunIndex=nextIndex;renderCase(pressModel.cases[nextIndex].id);}else renderScene('E07');};
if(['127.0.0.1','localhost'].includes(location.hostname))window.__chanceryQA={reachEnding:(id)=>{state.tags={};state.dossierEvidence=0;if(id==='KHOMYAKOV')state.tags.slavophile_affinity=2;if(id==='BELINSKY'){state.tags.press_freedom=2;state.tags.legalism=1;}if(id==='HERZEN'){state.tags.press_freedom=2;state.tags.westernism=1;}if(id==='DOSTOEVSKY_PETRASHEVSKY')state.dossierEvidence=3;showEnding();return $('#endingTitle').textContent;}};
function mountCaseEvidence(caseId){const list=$('#caseEvidenceList');if(!list)return;const all=dialogueData[caseId]||[];const entries=[...all.filter(line=>line.evidence_class==='DIRECT').slice(0,7),...all.filter(line=>String(line.case_field||'').startsWith('optional')).slice(0,4)];list.hidden=!entries.length;list.innerHTML=entries.length?`<strong>연결된 원문·분기 발췌 · ${entries.length}건</strong>`:'';entries.forEach((line,index)=>{const button=document.createElement('button');button.textContent=`${index+1}. ${line.text}`;button.onclick=()=>{setSourceReading({sourceId:line.source_ids[0],scanUrl:'',scanCaption:`원문 위치 · ${line.locator||'연결된 출처'}`,transcription:line.original||line.text,translation:line.text});addTag('source_excerpt');showSourceTab('transcription');};list.append(button);});}
const evidenceRenderCase=renderCase;renderCase=(id)=>{evidenceRenderCase(id);mountCaseEvidence(id);};const evidenceRenderScene=renderScene;renderScene=(id)=>{evidenceRenderScene(id);const list=$('#caseEvidenceList');if(list)list.hidden=true;};
function mountCaseReview(caseId){const list=$('#caseReviewList');if(!list)return;const c=caseData[caseId];if(!c){list.hidden=true;return;}state.reviewItems=state.reviewItems||[];list.hidden=false;list.innerHTML='';[...c.incoming.map((text,index)=>({text,index,kind:'도착'})),...c.review.map((text,index)=>({text,index,kind:'검토'}))].forEach(item=>{const key=`${caseId}:${item.kind}:${item.index}`;const button=document.createElement('button');button.className=state.reviewItems.includes(key)?'selected':'';button.innerHTML=`${item.text}<small>${item.kind} 문서 · ${state.reviewItems.includes(key)?'확인함':'열어 보기'}</small>`;button.onclick=()=>{if(!state.reviewItems.includes(key)){state.reviewItems.push(key);addTag(`review_${caseId}_${item.index}`);}button.classList.add('selected');button.querySelector('small').textContent=`${item.kind} 문서 · 확인함`;setSourceReading({sourceId:c.casePackId,scanUrl:'',scanCaption:`${c.year}년 ${c.title} · ${item.kind} 항목`,transcription:item.text,translation:c.review[0]||c.lead});drawer(true);};list.append(button);});}
const reviewRenderCase=renderCase;renderCase=(id)=>{reviewRenderCase(id);mountCaseReview(id);};const reviewRenderScene=renderScene;renderScene=(id)=>{reviewRenderScene(id);const list=$('#caseReviewList');if(list)list.hidden=true;};
const resetGame=$('#restart').onclick;$('#restart').onclick=()=>{state.reviewItems=[];resetGame();};
const submitWithReview=submit;submit=()=>{if(state.scene==='CASE'){const reviewed=(state.reviewItems||[]).filter(key=>key.startsWith(`${state.caseId}:`)).length;if(reviewed<2){$('#instruction').textContent=`이 사건에서 문서 ${2-reviewed}건을 더 확인한 뒤 의견을 남기십시오.`;$('#caseReviewList')?.scrollIntoView({block:'nearest'});return;}}submitWithReview();};$('#submitReply').onclick=submit;
/* V5 clarity pass: translation is the default reading layer and the task is always singular. */
const setCurrentTask=(text)=>{const el=$('#currentTask span');if(el)el.textContent=text;};
$('#translationBtn').onclick=()=>{const visible=!$('#paperTranslation').hidden;$('#paperTranslation').hidden=visible;$('#translationBtn').textContent=visible?'한국어 번역 보기':'원문 아래 번역 닫기';};
const claritySceneRender=renderScene;renderScene=(id)=>{claritySceneRender(id);setCurrentTask(state.documentsRead.includes(id)?'표시한 문장을 검토한 뒤, 문서를 상신하거나 보류하십시오.':'한국어 번역을 확인한 뒤, 검토할 문장을 표시하십시오.');};
const clarityCaseRender=renderCase;renderCase=(id)=>{clarityCaseRender(id);setCurrentTask('도착 문서와 검토 문서를 확인한 뒤, 처리할 문장을 표시하십시오.');};
const claritySubmit=submit;submit=()=>{claritySubmit();if(state.scene==='CASE')setCurrentTask('문서를 확인했습니다. 이제 어디로 보낼지 선택하십시오.');else setCurrentTask('문장이 표시되었습니다. 이제 문서를 상신하거나 보류하십시오.');};$('#submitReply').onclick=submit;
window.addEventListener('window-focus',(event)=>{if(event.detail?.source==='window-controller')return;setCurrentTask('창밖을 확인했습니다. 눈 섞인 바람과 마차 소리를 들은 뒤 책상으로 돌아가십시오.');$('#dialogue').textContent='창문을 열어젖히지 않아도 바깥의 종소리와 젖은 돌길 냄새가 방 안까지 들어옵니다.';$('#routeState').innerHTML='<b>창밖 · 상트페테르부르크</b><span>늦은 오후의 눈발과 안개 · 문서는 책상 위에 남아 있습니다.</span>';});
