const canvas = document.querySelector('#deskCanvas');
if (canvas) {
  try {
    const THREE = await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js');
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x67452f);
    const camera = new THREE.PerspectiveCamera(32, 1, .1, 40);
    camera.position.set(0, 7.4, 8.8);
    camera.lookAt(0, 0, 0);
    const renderer = new THREE.WebGLRenderer({canvas, antialias:true, alpha:true, powerPreference:'high-performance'});
    renderer.setPixelRatio(Math.min(devicePixelRatio, 1.35));
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    renderer.shadowMap.autoUpdate = false;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.05;
    const wood = new THREE.MeshStandardMaterial({color:0x603b26, roughness:.78});
    const darkWood = new THREE.MeshStandardMaterial({color:0x302017, roughness:.86});
    const brass = new THREE.MeshStandardMaterial({color:0xb1884d, roughness:.34, metalness:.58});
    const paper = new THREE.MeshStandardMaterial({color:0xd8c49b, roughness:.92});
    const ink = new THREE.MeshStandardMaterial({color:0x20232a, roughness:.38, metalness:.12});
    const red = new THREE.MeshStandardMaterial({color:0x7d3028, roughness:.68});
    const brassLight = new THREE.PointLight(0xffc477, 1.5, 7);
    brassLight.position.set(-3.7, 3.8, 1.2);
    scene.add(new THREE.HemisphereLight(0xd7c7ad, 0x241712, 1.6), brassLight);
    const key = new THREE.DirectionalLight(0xffdfb0, 1.7);
    key.position.set(-4, 8, 5); key.castShadow = true; scene.add(key);
    const box = (w,h,d,mat,x,y,z,parent=scene) => { const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat); m.position.set(x,y,z); m.castShadow=false; m.receiveShadow=true; parent.add(m); return m; };
    const cyl = (r,h,mat,x,y,z,parent=scene,segments=12) => { const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),mat); m.position.set(x,y,z); m.castShadow=false; m.receiveShadow=true; parent.add(m); return m; };
    const prop = (id,label,action,group,x,z) => { group.position.x=x; group.position.z=z; group.userData={id,label,action}; scene.add(group); props.push(group); return group; };
    const props=[];
    box(15,.22,9,wood,0,-.18,0);
    box(15,.14,.24,darkWood,0,.02,-4.35); box(.24,.14,9,darkWood,-7.38,.02,0); box(.24,.14,9,darkWood,7.38,.02,0);
    // The room opening is part of the desk scene: recess, glazing plate, jambs and sill.
    const windowArchitecture=new THREE.Group(); windowArchitecture.name='architectural-window-opening'; windowArchitecture.position.set(4.25,3.45,-3.45);
    const windowWallMat=new THREE.MeshStandardMaterial({color:0x4d3024,roughness:.88});
    box(3.25,2.55,.28,windowWallMat,0,0,.16,windowArchitecture);
    const recessMat=new THREE.MeshStandardMaterial({color:0x172329,roughness:.42,metalness:.06,transparent:true,opacity:.92});
    box(2.65,1.95,.12,recessMat,0,.12,0,windowArchitecture);
    const windowFrameMat=new THREE.MeshStandardMaterial({color:0x6f492e,roughness:.72});
    box(2.95,.18,.26,windowFrameMat,0,1.16,.08,windowArchitecture); box(2.95,.18,.26,windowFrameMat,0,-.92,.08,windowArchitecture);
    box(.18,2.18,.26,windowFrameMat,-1.38,.12,.08,windowArchitecture); box(.18,2.18,.26,windowFrameMat,1.38,.12,.08,windowArchitecture);
    box(.12,2.02,.3,brass,0,.12,.04,windowArchitecture); box(2.78,.12,.3,brass,0,.12,.04,windowArchitecture);
    box(3.25,.22,.68,windowFrameMat,0,-1.28,.18,windowArchitecture);
    windowArchitecture.userData={id:'architectural-window',label:'실제 창문 개구부',action:'벽 안쪽의 창문 recess와 창턱을 확인합니다.'}; scene.add(windowArchitecture); props.push(windowArchitecture);
    const notebook=new THREE.Group(); notebook.name='notebook-object-space'; notebook.position.set(-4.25,.2,1.62); notebook.rotation.y=-.14;
    const coverMat=new THREE.MeshStandardMaterial({color:0x5a2d26,roughness:.72}); const pageMat=new THREE.MeshStandardMaterial({color:0xe6d3a5,roughness:.94});
    box(1.85,.13,1.28,coverMat,0,0,0,notebook); box(1.62,.025,1.08,pageMat,.08,.085,0,notebook); box(.08,.16,1.34,brass,-.86,.02,0,notebook);
    notebook.userData={id:'notebook',label:'개인 수첩',action:'두꺼운 표지와 실제 페이지에 메모를 남깁니다.'}; scene.add(notebook); props.push(notebook);
    const quill=new THREE.Group(); cyl(.035,1.55,ink,0,.22,0,quill,8).rotation.z=-.32; const feather=new THREE.Mesh(new THREE.ConeGeometry(.14,.95,8),new THREE.MeshStandardMaterial({color:0xe5d9bd,roughness:.9})); feather.position.set(.22,.98,0); feather.rotation.z=-.55; quill.add(feather); prop('quill','깃펜','끝을 잉크에 적셔 여백에 표시합니다.',quill,-5.2,-1.4);
    const inkwell=new THREE.Group(); cyl(.34,.42,ink,0,.2,0,inkwell,16); cyl(.18,.12,brass,0,.47,0,inkwell,12); prop('inkwell','잉크병','짙은 잉크가 아직 마르지 않았습니다.',inkwell,-4.25,-.6);
    const knife=new THREE.Group(); box(.78,.1,.18,darkWood,0,.12,0,knife); const blade=box(.78,.035,.12,brass,.48,.18,0,knife); blade.rotation.y=.08; prop('pen-knife','펜칼','교정쇄 가장자리를 정리합니다.',knife,-3.4,-2.2);
    const wax=new THREE.Group(); cyl(.13,.46,red,0,.22,0,wax,10); prop('sealing-wax','봉인 왁스','봉인할 문서에 붉은 왁스를 떨어뜨립니다.',wax,4.75,-2.2);
    const seal=new THREE.Group(); cyl(.3,.12,brass,0,.15,0,seal,16); cyl(.08,.45,darkWood,0,.4,0,seal,10); prop('seal','관청 도장','도장을 눌러 전달 경로를 확정합니다.',seal,5.55,-1.2);
    const shaker=new THREE.Group(); cyl(.27,.48,brass,0,.24,0,shaker,10); const cap=cyl(.2,.13,darkWood,0,.55,0,shaker,10); cap.rotation.z=.2; prop('sand-shaker','모래 뿌리개','젖은 잉크 위에 고운 모래를 뿌립니다.',shaker,-5.8,1.3);
    const ledger=new THREE.Group(); box(1.25,.48,1.7,darkWood,0,.3,0,ledger); box(1.08,.025,1.48,red,0,.56,0,ledger); prop('ledger','대장','이 문서의 접수 번호와 흔적을 대조합니다.',ledger,-2.55,2.35);
    const periodical=new THREE.Group(); box(1.32,.22,1.65,red,0,.14,0,periodical); box(1.16,.03,1.47,paper,0,.28,0,periodical); prop('periodical','제본 잡지','해당 호의 앞뒤 지면을 펼칩니다.',periodical,2.25,2.45);
    const proof=new THREE.Group(); box(1.7,.04,1.05,paper,0,.06,0,proof); box(1.52,.02,.03,ink,0,.09,-.28,proof); prop('proof-sheet','교정쇄','삭제 표시와 편집자의 손을 확인합니다.',proof,3.8,1.65);
    const folder=new THREE.Group(); box(1.45,.34,1.05,darkWood,0,.2,0,folder); box(1.25,.025,.86,red,0,.4,.02,folder); prop('official-folder','공식 자료철','상급자에게 올릴 서류를 묶습니다.',folder,4.8,1.0);
    const envelope=new THREE.Group(); box(1.3,.04,.86,paper,0,.08,0,envelope); const flap=new THREE.Mesh(new THREE.ConeGeometry(.52,.62,3),paper); flap.rotation.x=Math.PI/2; flap.rotation.z=Math.PI; flap.scale.set(1,.45,1); flap.position.set(0,.13,0); envelope.add(flap); prop('envelope','봉투','봉투를 열어 다음 전달자의 흔적을 봅니다.',envelope,5.55,.15);
    const ribbon=new THREE.Group(); const ribbonMesh=new THREE.Mesh(new THREE.TorusGeometry(.32,.055,8,20),new THREE.MeshStandardMaterial({color:0x6c2630,roughness:.62})); ribbonMesh.rotation.x=Math.PI/2; ribbon.add(ribbonMesh); prop('ribbon','리본 끈','같은 묶음에 속한 문서를 연결합니다.',ribbon,4.55,2.65);
    const lamp=new THREE.Group(); cyl(.38,.12,brass,0,.08,0,lamp,16); cyl(.055,1.7,darkWood,0,.9,0,lamp,8); const shade=new THREE.Mesh(new THREE.ConeGeometry(.42,.42,12,1,true),new THREE.MeshStandardMaterial({color:0xc09155,roughness:.7,side:THREE.DoubleSide})); shade.position.set(0,1.8,0); lamp.add(shade); const lampLight=new THREE.PointLight(0xffbb6d,.7,3); lampLight.position.set(0,1.65,0); lamp.add(lampLight); prop('lamp','등불','등불 가까이에서 희미한 활자를 읽습니다.',lamp,-5.7,-2.5);
    const scissors=new THREE.Group(); const s1=new THREE.Mesh(new THREE.TorusGeometry(.2,.045,8,16,Math.PI*1.7),brass); const s2=s1.clone(); s1.rotation.z=.45; s2.rotation.z=-.45; scissors.add(s1,s2); prop('scissors','가위','봉투 끈을 자릅니다.',scissors,1.2,-3.1);
    const blotter=new THREE.Group(); box(1.5,.08,.8,darkWood,0,.08,0,blotter); box(1.32,.025,.62,red,0,.14,0,blotter); prop('blotter','압지','방금 쓴 문장을 눌러 번짐을 막습니다.',blotter,-1.05,-3.1);
    const drawer=new THREE.Group(); box(1.55,.52,.92,darkWood,0,.3,0,drawer); box(1.08,.24,.025,wood,0,.36,.47,drawer); cyl(.07,.08,brass,0,.4,.51,drawer,10).rotation.x=Math.PI/2; prop('drawer','서랍','보관한 편지와 도장을 꺼냅니다.',drawer,-1.35,3.15);
    const trayIn=new THREE.Group(); box(1.65,.16,1.2,wood,0,.12,0,trayIn); box(1.45,.08,1.0,paper,0,.23,0,trayIn); prop('incoming-tray','받은 서류함','도착한 문서를 책상 중앙으로 옮깁니다.',trayIn,3.05,-.95);
    const trayOut=new THREE.Group(); box(1.65,.16,1.2,wood,0,.12,0,trayOut); box(1.45,.08,1.0,red,0,.23,0,trayOut); prop('outgoing-tray','보낼 서류함','봉인된 문서를 다음 방으로 보냅니다.',trayOut,2.8,-2.55);
    const card=new THREE.Group(); box(.9,.035,.54,paper,0,.07,0,card); prop('calling-card','방문 카드','다음 방문자의 이름과 시각을 확인합니다.',card,-5.75,.15);
    const watch=new THREE.Group(); const watchFace=new THREE.Mesh(new THREE.CylinderGeometry(.32,.32,.08,24),brass); watchFace.rotation.x=Math.PI/2; watchFace.position.y=.15; watch.add(watchFace); const chain=new THREE.Mesh(new THREE.TorusGeometry(.46,.025,8,20),brass); chain.rotation.x=Math.PI/2; chain.position.y=.2; watch.add(chain); prop('pocket-watch','회중시계','전달 시간을 기록합니다.',watch,-3.1,1.3);
    const raycaster=new THREE.Raycaster(); const pointer=new THREE.Vector2(); let selected=null; let dragging=false; let lastX=0; let cameraFocus='desk';
    const deskCameraPosition=new THREE.Vector3(0,7.4,8.8), deskCameraTarget=new THREE.Vector3(0,0,0), focusCameraPosition=new THREE.Vector3(4.25,4.9,2.2), focusCameraTarget=new THREE.Vector3(4.25,3.45,-3.45), notebookCameraPosition=new THREE.Vector3(-3.7,3.7,2.8), notebookCameraTarget=new THREE.Vector3(-4.25,.2,1.62), cameraTarget=new THREE.Vector3();
    const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};
    addEventListener('resize',resize); resize(); requestAnimationFrame(resize);
    const hit=(event)=>{const r=canvas.getBoundingClientRect();pointer.x=((event.clientX-r.left)/r.width)*2-1;pointer.y=-((event.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const intersections=raycaster.intersectObjects(props,true);return intersections.find((entry)=>{let current=entry.object;while(current&&current!==scene){if(props.includes(current))return true;current=current.parent;}return false;});};
    const rootOf=(object)=>{let current=object;while(current.parent&&current.parent!==scene)current=current.parent;return current;};
    canvas.addEventListener('pointerdown',(event)=>{const entry=hit(event);if(!entry)return;selected=rootOf(entry.object);dragging=true;lastX=event.clientX;canvas.setPointerCapture(event.pointerId);});
    canvas.addEventListener('pointermove',(event)=>{if(!dragging||!selected)return;selected.rotation.y+=(event.clientX-lastX)*.012;lastX=event.clientX;});
    canvas.addEventListener('pointerup',(event)=>{if(!selected)return;dragging=false;canvas.releasePointerCapture(event.pointerId);const data=selected.userData;window.dispatchEvent(new CustomEvent('desk-prop',{detail:{id:data.id,label:data.label,action:`${data.action} 선택한 소품을 드래그해 방향을 돌릴 수 있습니다.`}}));});
    canvas.addEventListener('dblclick',(event)=>{const entry=hit(event);if(!entry)return;const item=rootOf(entry.object);const data=item.userData;if(['envelope','ledger','official-folder','drawer','incoming-tray','outgoing-tray'].includes(data.id)){item.rotation.x=item.rotation.x ? 0 : -.22;window.dispatchEvent(new CustomEvent('desk-prop',{detail:{id:data.id,label:data.label,action:`${data.action} 열림 상태를 확인했습니다.`}}));}});
    canvas.addEventListener('wheel',(event)=>{if(selected){selected.rotation.y+=event.deltaY*.002;event.preventDefault();}},{passive:false});
    const vista=document.querySelector('.petersburg-window');
    const stage=document.querySelector('.document-stage');
    stage?.addEventListener('pointermove',(event)=>{
      if(!vista)return;
      const r=stage.getBoundingClientRect();
      const x=Math.max(-1,Math.min(1,((event.clientX-r.left)/r.width-.5)*2));
      const y=Math.max(-1,Math.min(1,((event.clientY-r.top)/r.height-.5)*2));
      vista.style.setProperty('--vista-x',`${(-x*7).toFixed(2)}px`);
      vista.style.setProperty('--vista-y',`${(-y*4).toFixed(2)}px`);
    });
    stage?.addEventListener('pointerleave',()=>{vista?.style.setProperty('--vista-x','0px');vista?.style.setProperty('--vista-y','0px');});
    renderer.shadowMap.needsUpdate=true;
    window.addEventListener('window-view-change',event=>{cameraFocus=event.detail?.open?'window':'desk';});
    window.addEventListener('notebook-focus',event=>{cameraFocus=event.detail?.open?'notebook':'desk';});
    const clock=new THREE.Clock(); let lastRender=0; const frame=(now=0)=>{requestAnimationFrame(frame);if(document.hidden||now-lastRender<33)return;lastRender=now;const t=clock.getElapsedTime();lampLight.intensity=.68+Math.sin(t*3.2)*.06;const position=cameraFocus==='window'?focusCameraPosition:cameraFocus==='notebook'?notebookCameraPosition:deskCameraPosition;const target=cameraFocus==='window'?focusCameraTarget:cameraFocus==='notebook'?notebookCameraTarget:deskCameraTarget;camera.position.lerp(position,.08);cameraTarget.lerp(target,.08);camera.lookAt(cameraTarget);windowArchitecture.rotation.y=Math.sin(t*.35)*.004;renderer.render(scene,camera);}; frame();
    window.__deskMetrics=()=>({drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,textures:renderer.info.memory.textures,geometries:renderer.info.memory.geometries,dpr:renderer.getPixelRatio(),propCount:props.length});
    document.querySelector('.document-stage')?.classList.add('desk-three-ready');
    canvas.dataset.threeLoaded = 'local';
    canvas.dataset.fallback = 'false';
    window.__threeRuntime = {loaded:true, local:true, fallback:false, renderer, scene, camera, canvas, getMetrics:window.__deskMetrics, cameraFocus:()=>cameraFocus};
  } catch (error) {
    canvas.dataset.threeLoaded = 'error';
    canvas.dataset.fallback = 'true';
    window.__threeRuntime = {loaded:false, local:true, fallback:true, error:String(error)};
    console.error('Local Three.js desk runtime failed.', error);
  }
}
