// Authored 1847 courier street; geometry is reconstructed from route-evidence.json.
const walk = document.querySelector('.walk-scene');
const canvas = document.createElement('canvas');
canvas.id='threeWalkCanvas'; canvas.setAttribute('aria-label','1847년 겨울 상트페테르부르크 거리'); walk.prepend(canvas);

try {
  const THREE = await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js');
  const scene=new THREE.Scene(); scene.background=new THREE.Color(0x59676b); scene.fog=new THREE.Fog(0x59676b,35,145);
  const camera=new THREE.PerspectiveCamera(58,1,.1,220); camera.position.set(0,1.68,16);
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05;
  const loader=new THREE.TextureLoader(); const woodMap=loader.load('assets/wood-grain.svg'); const woodRough=loader.load('assets/wood-roughness.svg'); const woodNormal=loader.load('assets/wood-normal.svg'); const plasterMap=loader.load('assets/paper-fiber.svg');
  const mat=(color,rough=.86,kind='plain',metal=0)=>kind==='wood'?new THREE.MeshStandardMaterial({color,map:woodMap,roughnessMap:woodRough,normalMap:woodNormal,roughness:rough,metalness:metal,normalScale:new THREE.Vector2(.16,.16)}):kind==='plaster'?new THREE.MeshStandardMaterial({color,map:plasterMap,roughness:rough,metalness:metal}):new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});
  const darkWood=mat(0x3a241b,.94,'wood'), stone=mat(0x6a6259,.98), roadMat=mat(0x3a3733,1,'wood'), brass=mat(0xa77f42,.55,'plain',.35), windowMat=new THREE.MeshStandardMaterial({color:0x243945,roughness:.32}), warmWindow=new THREE.MeshStandardMaterial({color:0xb6814d,emissive:0x5e3519,emissiveIntensity:.6,roughness:.65});
  scene.add(new THREE.HemisphereLight(0xb8c6c7,0x211a18,1.55)); const sun=new THREE.DirectionalLight(0xffd6a1,2.15); sun.position.set(-22,32,18); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun); const dusk=new THREE.DirectionalLight(0x6d8490,.55); dusk.position.set(20,12,-35); scene.add(dusk);
  const cube=(w,h,d,material,x,y,z,parent=scene)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;};
  const cylinder=(r,h,material,x,y,z,parent=scene,radial=8)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,radial),material);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;};
  const signMaterial=(text)=>{const c=document.createElement('canvas');c.width=640;c.height=112;const ctx=c.getContext('2d');ctx.fillStyle='#3d281e';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#c09b5a';ctx.lineWidth=6;ctx.strokeRect(8,8,c.width-16,c.height-16);ctx.fillStyle='#f0d49a';ctx.font='bold 44px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,c.width/2,c.height/2);return new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c)});};
  cube(28,.18,154,roadMat,0,-.12,-45).receiveShadow=true;
  const stones=[stone,mat(0x625d57,.99),mat(0x736b61,.99)];for(let z=10;z>-118;z-=2.2)for(const x of [-8.5,-6.1,-3.7,-1.3,1.1,3.5,5.9,8.3]){const seed=Math.sin(z*12.7+x*8.3)*43758.5453;const n=seed-Math.floor(seed);const s=cube(1.55+n*.42,.035,.78+n*.22,stones[Math.floor(n*3)],x+(n-.5)*.16,.015+(n*.012),z+(n-.5)*.15);s.rotation.y=(n-.5)*.11;}
  cube(2.7,.16,150,mat(0x806852,.92),-6.6,.02,-45); cube(2.7,.16,150,mat(0x806852,.92),6.6,.02,-45); cube(.12,.035,132,brass,0,.12,-48);
  const puddleMat=new THREE.MeshStandardMaterial({color:0x26353a,roughness:.2,metalness:.22,transparent:true,opacity:.56});
  for(const [x,z,w,d] of [[-3.3,-9,2.4,.8],[2.8,-37,1.7,.65],[-1.9,-67,2.1,.7],[3.1,-96,2.5,.85],[-2.8,-121,1.6,.55]]){const puddle=new THREE.Mesh(new THREE.CircleGeometry(1,28),puddleMat);puddle.scale.set(w,d,1);puddle.rotation.x=-Math.PI/2;puddle.position.set(x,.045,z);scene.add(puddle);}
  const addWindow=(parent,x,y,z,lit=false)=>{cube(.82,1.16,.08,lit?warmWindow:windowMat,x,y,z,parent);cube(.92,.08,.12,darkWood,x,y-.58,z-.04,parent);cube(.08,1.25,.12,darkWood,x-.46,y,z-.04,parent);cube(.08,1.25,.12,darkWood,x+.46,y,z-.04,parent);cube(.06,1.12,.13,darkWood,x,y,z-.05,parent);};
  const addDoor=(parent,x,y,z)=>{cube(1.35,2.35,.16,darkWood,x,y,z,parent);cube(.12,2.1,.18,brass,x-.53,y,z-.1,parent);cube(.12,2.1,.18,brass,x+.53,y,z-.1,parent);cylinder(.07,.08,brass,x+.34,y,z-.17,parent,10).rotation.x=Math.PI/2;};
  const building=(x,z,w,h,d,color,label)=>{const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);cube(w,h,d,mat(color,.89,'plaster'),0,h/2,0,g);cube(w+.5,.28,d+.18,mat(0x8b725c,.8),0,h-.22,0,g);cube(w+.75,.32,d+.25,darkWood,0,h+.06,0,g);for(let bx=-w/2+1.35;bx<w/2-.5;bx+=2.15)for(let by=1.65;by<h-1;by+=2.35)addWindow(g,bx,by,d/2+.07,(Math.round(bx+by)%4===0));addDoor(g,Math.min(w/2-1.3,0),1.18,d/2+.1);if(label){const sign=new THREE.Mesh(new THREE.PlaneGeometry(2.8,.49),signMaterial(label));sign.position.set(Math.min(w/2-1.4,1.2),h-1.1,d/2+.2);g.add(sign);}return g;};
  building(-8,-22,10,9,10,0x9b806b,'КАНЦЕЛЯРИЯ'); building(8,-48,11,12,10,0x8d6d60,'ГОСТИНИЦА'); building(-8,-82,10,9,10,0x9a8566,'КОМИТЕТЪ'); building(7,-108,13,7,10,0x846c58,'КНИГИ'); building(-7,-132,11,12,10,0x8d7a6f,'АРХИВЪ');
  const lampLights=[]; for(const z of [-4,-30,-56,-84,-112,-138]){cylinder(.075,3.5,darkWood,-3.9,1.75,z,scene,8);cylinder(.22,.12,brass,-3.9,3.55,z,scene,10);cylinder(.12,.18,warmWindow,-3.9,3.37,z,scene,10).rotation.x=Math.PI/2;const l=new THREE.PointLight(0xffbd73,.55,9,2);l.position.set(-3.9,3.35,z);scene.add(l);lampLights.push(l);}
  const glowCanvas=document.createElement('canvas');glowCanvas.width=128;glowCanvas.height=128;const glowCtx=glowCanvas.getContext('2d');const glow=glowCtx.createRadialGradient(64,64,4,64,64,64);glow.addColorStop(0,'rgba(255,215,145,.42)');glow.addColorStop(.35,'rgba(255,176,91,.16)');glow.addColorStop(1,'rgba(255,176,91,0)');glowCtx.fillStyle=glow;glowCtx.fillRect(0,0,128,128);const glowMat=new THREE.SpriteMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});for(const z of [-4,-30,-56,-84,-112,-138]){const halo=new THREE.Sprite(glowMat);halo.scale.set(5.2,5.2,1);halo.position.set(-3.9,3.35,z);scene.add(halo);}
  const carriage=new THREE.Group();carriage.position.set(2.1,0,-18);scene.add(carriage);cube(2.2,.95,2.7,mat(0x4b2b21,.72,'wood'),0,1.05,0,carriage);cube(1.65,.7,1.35,mat(0x6b4632,.8,'wood'),0,1.86,.1,carriage);for(const x of [-1.1,1.1])for(const z of [-.86,.86]){const w=cylinder(.38,.14,darkWood,x,.48,z,carriage,16);w.rotation.z=Math.PI/2;}cube(.08,.08,3.5,darkWood,0,.92,-1.9,carriage).rotation.x=.12;
  const walkers=[]; for(const z of [-12,-29,-57,-75,-101]){const p=new THREE.Group();p.position.set(z%5-1.2,0,z);scene.add(p);cylinder(.21,1.38,mat(0x373333,.95),0,.82,0,p,8);cylinder(.24,.38,mat(0x2a2524,.9),0,1.68,0,p,8);cube(.52,.08,1.8,mat(0x252120,.95),0,1.58,0,p);walkers.push({group:p,baseX:p.position.x,phase:z});}
  const weatherPositions=new Float32Array(620*3);for(let i=0;i<620;i++){weatherPositions[i*3]=(Math.random()-.5)*24;weatherPositions[i*3+1]=Math.random()*13;weatherPositions[i*3+2]=16-Math.random()*158;}const weatherGeometry=new THREE.BufferGeometry();weatherGeometry.setAttribute('position',new THREE.BufferAttribute(weatherPositions,3));const weather=new THREE.Points(weatherGeometry,new THREE.PointsMaterial({color:0xf2eee4,size:.095,transparent:true,opacity:.78,depthWrite:false}));scene.add(weather);
  const mistCanvas=document.createElement('canvas');mistCanvas.width=256;mistCanvas.height=128;const mistCtx=mistCanvas.getContext('2d');const mistGradient=mistCtx.createRadialGradient(128,64,8,128,64,128);mistGradient.addColorStop(0,'rgba(197,213,214,.2)');mistGradient.addColorStop(.55,'rgba(174,198,201,.08)');mistGradient.addColorStop(1,'rgba(174,198,201,0)');mistCtx.fillStyle=mistGradient;mistCtx.fillRect(0,0,256,128);const mistMat=new THREE.SpriteMaterial({map:new THREE.CanvasTexture(mistCanvas),transparent:true,depthWrite:false,opacity:.75});const mists=[];for(let i=0;i<9;i++){const fogBank=new THREE.Sprite(mistMat);fogBank.scale.set(16+Math.random()*8,4+Math.random()*2,1);fogBank.position.set((Math.random()-.5)*12,1.1+Math.random()*.9,-8-i*16);scene.add(fogBank);mists.push({sprite:fogBank,phase:Math.random()*6});}
  const smokePositions=new Float32Array(150*3);for(let i=0;i<150;i++){const chimney=i%3;smokePositions[i*3]=[-8,8,-7][chimney]+(Math.random()-.5)*.8;smokePositions[i*3+1]=7+Math.random()*4;smokePositions[i*3+2]=[-22,-48,-132][chimney]+(Math.random()-.5)*.7;}const smokeGeometry=new THREE.BufferGeometry();smokeGeometry.setAttribute('position',new THREE.BufferAttribute(smokePositions,3));const smoke=new THREE.Points(smokeGeometry,new THREE.PointsMaterial({color:0xb8b7ae,size:.22,transparent:true,opacity:.18,depthWrite:false}));scene.add(smoke);
  const lantern=cylinder(.12,.36,brass,0,1.4,0,scene,8);const playerLight=new THREE.PointLight(0xffc27c,.7,5,2);scene.add(playerLight);const walls=[{x:-8,z:-22,w:10,d:10},{x:8,z:-48,w:11,d:10},{x:-8,z:-82,w:10,d:10},{x:7,z:-108,w:13,d:10},{x:-7,z:-132,w:11,d:10}];const player={x:0,z:16};const keys=new Set();const clock=new THREE.Clock();let audio,frameSamples=[],frames=0;
  const weatherMeter=document.createElement('span');weatherMeter.className='walk-weather';weatherMeter.textContent='눈발 · 북서풍';walk.append(weatherMeter);const routeMeter=document.createElement('span');routeMeter.className='walk-route-meter';routeMeter.textContent='전달 거리 0m';walk.append(routeMeter);const controls=document.createElement('span');controls.className='walk-controls';controls.textContent='WASD / 방향키로 이동';walk.append(controls);
  function resize(){const r=walk.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();requestAnimationFrame(resize);addEventListener('walk-open',()=>{requestAnimationFrame(resize);setTimeout(resize,80);});
  function startSound(){if(audio)return;try{audio=new AudioContext();const master=audio.createGain();master.gain.value=.035;master.connect(audio.destination);const wind=audio.createBufferSource();const windBuffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const windData=windBuffer.getChannelData(0);for(let i=0;i<windData.length;i++)windData[i]=(Math.random()*2-1)*.22;wind.buffer=windBuffer;wind.loop=true;const windFilter=audio.createBiquadFilter();windFilter.type='lowpass';windFilter.frequency.value=520;const windGain=audio.createGain();windGain.gain.value=.22;wind.connect(windFilter).connect(windGain).connect(master);wind.start();const bell=()=>{const o=audio.createOscillator();const g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(392,audio.currentTime);o.frequency.exponentialRampToValueAtTime(330,audio.currentTime+.55);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+1.5);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+1.6);};const bellTimer=setInterval(bell,9000);addEventListener('pagehide',()=>clearInterval(bellTimer),{once:true});addEventListener('keyup',()=>{const o=audio.createOscillator();const g=audio.createGain();o.type='triangle';o.frequency.value=82;g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+.17);},{passive:true});}catch{}}
  const soundButton=document.createElement('button');soundButton.className='walk-sound';soundButton.textContent='공간음 켜기';soundButton.onclick=()=>{startSound();soundButton.textContent='공간음 켜짐';};walk.append(soundButton);addEventListener('walk-open',startSound,{once:false});addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
  function blocked(x,z){return walls.some(w=>Math.abs(x-w.x)<w.w/2+.75&&Math.abs(z-w.z)<w.d/2+.75);}
  function frame(){requestAnimationFrame(frame);if(document.hidden||!walk.isConnected)return;const dt=Math.min(clock.getDelta(),.05);const elapsed=clock.elapsedTime;const move=dt*3.1;let nx=player.x,nz=player.z;if(keys.has('w')||keys.has('arrowup'))nz-=move;if(keys.has('s')||keys.has('arrowdown'))nz+=move;if(keys.has('a')||keys.has('arrowleft'))nx-=move;if(keys.has('d')||keys.has('arrowright'))nx+=move;if(!blocked(nx,nz)){player.x=nx;player.z=nz;}player.x=Math.max(-4.8,Math.min(4.8,player.x));player.z=Math.max(-143,Math.min(16,player.z));camera.position.x+=(player.x-camera.position.x)*.16;camera.position.z+=(player.z-camera.position.z)*.16;camera.lookAt(camera.position.x,1.55,camera.position.z-30);lantern.position.set(player.x+.65,1.05,player.z-1.4);lantern.scale.setScalar(.32);playerLight.position.set(player.x,1.8,player.z-1);carriage.position.x=2.1+Math.sin(elapsed*.45)*.75;carriage.rotation.y=Math.sin(elapsed*.45)*.025;walkers.forEach((w)=>{w.group.position.x=w.baseX+Math.sin(elapsed*1.3+w.phase)*.35;w.group.position.y=Math.abs(Math.sin(elapsed*2+w.phase))*.035;});lampLights.forEach((l,i)=>{l.intensity=.48+Math.sin(elapsed*3+i)*.06;});for(let i=0;i<620;i++){const j=i*3;weatherPositions[j]+=dt*(.18+((i%7)-3)*.015);weatherPositions[j+1]-=dt*(.55+(i%5)*.08);weatherPositions[j+2]+=dt*.28;if(weatherPositions[j+1]<.1)weatherPositions[j+1]=13;if(weatherPositions[j]>12)weatherPositions[j]=-12;if(weatherPositions[j+2]>18)weatherPositions[j+2]=-142;}for(const fog of mists){fog.sprite.position.x+=dt*(.12+Math.sin(elapsed+fog.phase)*.025);if(fog.sprite.position.x>14)fog.sprite.position.x=-14;}for(let i=0;i<150;i++){const j=i*3;smokePositions[j]+=(dt*.1);smokePositions[j+1]+=dt*(.18+(i%4)*.03);smokePositions[j+2]+=dt*.02;if(smokePositions[j+1]>12){const chimney=i%3;smokePositions[j]=[-8,8,-7][chimney]+(Math.random()-.5)*.8;smokePositions[j+1]=7;smokePositions[j+2]=[-22,-48,-132][chimney]+(Math.random()-.5)*.7;}}weatherGeometry.attributes.position.needsUpdate=true;smokeGeometry.attributes.position.needsUpdate=true;routeMeter.textContent=`전달 거리 ${Math.round(Math.max(0,16-player.z))}m`;renderer.render(scene,camera);}frame();walk.classList.add('three-ready');
}catch(error){console.error('Local Three.js courier runtime failed.',error);}
